# Generated by Django 4.2.19 on 2025-02-21 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('picture', models.ImageField(upload_to='listening/', verbose_name='Rasm')),
                ('submitters', models.IntegerField(default=0, verbose_name='Yuboruvchilar soni')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language', verbose_name='Til')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('submitters', models.IntegerField(default=0, verbose_name='Yuboruvchilar soni')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language', verbose_name='Til')),
            ],
        ),
        migrations.CreateModel(
            name='Speaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('picture', models.ImageField(upload_to='speaking/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('submitters', models.IntegerField(default=0, verbose_name='Yuboruvchilar soni')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language', verbose_name='Til')),
            ],
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='writing/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('task1', models.TextField()),
                ('task2', models.TextField()),
                ('submitters', models.IntegerField(default=0, verbose_name='Yuboruvchilar soni')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language', verbose_name='Til')),
            ],
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_listening', models.BooleanField(default=False)),
                ('listening_result', models.PositiveSmallIntegerField(default=0, verbose_name='Listening natijasi')),
                ('listening_user_options', models.JSONField(blank=True, null=True)),
                ('done_reading', models.BooleanField(default=False)),
                ('reading_result', models.PositiveSmallIntegerField(default=0, verbose_name='Reading natijasi')),
                ('reading_user_options', models.JSONField(blank=True, null=True)),
                ('done_writing', models.BooleanField(default=False)),
                ('result', models.PositiveSmallIntegerField(default=0, verbose_name='Writing natijasi')),
                ('writing_user_options', models.JSONField(blank=True, null=True)),
                ('done_speaking', models.BooleanField(default=False)),
                ('speaking_result', models.PositiveSmallIntegerField(default=0, verbose_name='Speaking natijasi')),
                ('speaking_user_options', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language', verbose_name='Til')),
                ('listening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.listening', verbose_name='Listening')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.reading', verbose_name='Reading')),
                ('speaking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.speaking', verbose_name='Speaking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('writing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.writing', verbose_name='Writing')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='tests/pictures/', verbose_name='Rasm')),
                ('audio', models.FileField(blank=True, null=True, upload_to='tests/audio/', verbose_name='Audio')),
                ('text_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Matn sarlavhasi')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Test matni')),
                ('options', models.TextField(blank=True, null=True, verbose_name='Variantlar')),
                ('sample', models.TextField(blank=True, null=True, verbose_name='Misol')),
                ('constraints', models.TextField(blank=True, null=True, verbose_name='Shartlar')),
                ('order', models.PositiveSmallIntegerField()),
                ('listening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.listening', verbose_name='Listening')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.reading', verbose_name='Reading')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Test Rasmi')),
                ('answer', models.CharField(blank=True, max_length=150, null=True, verbose_name='Javob')),
                ('has_options', models.BooleanField(default=True, verbose_name='Variantlar mavjud')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multilevel.test', verbose_name='Savol testi')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Variant')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri variant")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multilevel.question', verbose_name='Variant savoli')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
            },
        ),
    ]
