# Generated by Django 4.2.19 on 2025-02-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('multilevel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Listening', 'Listening'), ('Reading', 'Reading'), ('Writing', 'Writing'), ('Speaking', 'Speaking')], max_length=50, verbose_name="Bo'lim turi")),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('submitters', models.IntegerField(default=0, verbose_name='Yuboruvchilar soni')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language', verbose_name='Til')),
            ],
        ),
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language', verbose_name='Til')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.section', verbose_name="Bo'lim")),
            ],
        ),
        migrations.RemoveField(
            model_name='reading',
            name='language',
        ),
        migrations.RemoveField(
            model_name='speaking',
            name='language',
        ),
        migrations.RemoveField(
            model_name='writing',
            name='language',
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': "Bo'lim ", 'verbose_name_plural': "Bo'limlar "},
        ),
        migrations.AlterModelOptions(
            name='usertest',
            options={'verbose_name': 'Foydalanuvchi testi', 'verbose_name_plural': 'Foydalanuvchi testlari'},
        ),
        migrations.RenameField(
            model_name='usertest',
            old_name='listening_user_options',
            new_name='user_options',
        ),
        migrations.RemoveField(
            model_name='test',
            name='listening',
        ),
        migrations.RemoveField(
            model_name='test',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='done_listening',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='done_reading',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='done_speaking',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='done_writing',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='language',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='listening',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='listening_result',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='reading_result',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='reading_user_options',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='speaking',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='speaking_result',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='speaking_user_options',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='writing',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='writing_user_options',
        ),
        migrations.AddField(
            model_name='usertest',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multilevel.test', verbose_name='Test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertest',
            name='result',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Natija'),
        ),
        migrations.DeleteModel(
            name='Listening',
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.DeleteModel(
            name='Speaking',
        ),
        migrations.DeleteModel(
            name='Writing',
        ),
        migrations.AddField(
            model_name='usertestresult',
            name='user_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multilevel.usertest', verbose_name='Foydalanuvchi testi'),
        ),
        migrations.AddField(
            model_name='test',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.section', verbose_name='Section'),
        ),
    ]
