# Generated by Django 4.2.19 on 2025-03-10 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0002_section_usertestresult_remove_reading_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='usertest',
            name='score',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertest',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multilevel.option', verbose_name='Variant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multilevel.question', verbose_name='Savol')),
                ('user_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multilevel.usertest', verbose_name='Foydalanuvchi testi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi javobi',
                'verbose_name_plural': 'Foydalanuvchi javoblari',
            },
        ),
    ]
