# Generated by Django 4.2.19 on 2025-03-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('multilevel', '0003_usertest_end_time_usertest_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('completed', 'Completed')], default='created', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Natija')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.section', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Foydalanuvchi testi natijasi',
                'verbose_name_plural': 'Foydalanuvchi testi natijalari',
            },
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='option',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user_test',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='test',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='user_options',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_answer',
            field=models.CharField(default=1, max_length=20, verbose_name='Foydalanuvchi javobi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multilevel.option', verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language', verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Natija'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('completed', 'Completed')], default='created', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserTestResult',
        ),
        migrations.AddField(
            model_name='testresult',
            name='user_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multilevel.usertest', verbose_name='Foydalanuvchi testi'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='test_result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multilevel.testresult', verbose_name='Foydalanuvchi testi'),
            preserve_default=False,
        ),
    ]
