# Generated by Django 4.2.19 on 2025-03-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0004_testresult_remove_useranswer_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Test vaqti'),
        ),
    ]
