# Generated by Django 4.2.19 on 2025-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0005_section_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user_answer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Foydalanuvchi javobi'),
        ),
    ]
