# Generated by Django 4.2.19 on 2025-03-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0008_test_options_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='options_array',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Variantlar textlari'),
        ),
    ]
