# Generated by Django 4.2.19 on 2025-03-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0009_alter_test_options_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multilevel.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user_answer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Foydalanuvchi javobi'),
        ),
    ]
