# Generated by Django 4.2.19 on 2025-03-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0010_usertest_test_alter_useranswer_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('multilevel', 'Multilevel')], default='multilevel', max_length=20, verbose_name='Daraja'),
        ),
    ]
