# Generated by Django 4.2.19 on 2025-03-25 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0013_alter_section_options_alter_test_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multilevel.section', verbose_name="Bo'lim"),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multilevel.section', verbose_name="Bo'lim"),
        ),
    ]
