# Generated by Django 4.2.19 on 2025-03-25 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0014_alter_test_section_alter_testresult_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Yaratilgan vaqti'),
            preserve_default=False,
        ),
    ]
