# Generated by Django 4.2.19 on 2025-03-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('multilevel', '0015_testresult_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='language',
        ),
        migrations.RemoveField(
            model_name='section',
            name='level',
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('level', models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1'), ('multilevel', 'Multilevel')], default='multilevel', max_length=20, verbose_name='Daraja')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Imtihon narxi')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language', verbose_name='Til')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multilevel.exam', verbose_name='Imtihon'),
        ),
    ]
