# Generated by Django 4.2.19 on 2025-04-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0016_remove_section_language_remove_section_level_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multilevel.exam', verbose_name='Imtihon'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tranzaksiya ID'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', 'To‘langan'), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=20, verbose_name='To‘lov holati'),
        ),
    ]
