# Generated by Django 4.2.19 on 2025-04-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0017_usertest_exam_usertest_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Narxi'),
        ),
    ]
