# Generated by Django 4.2.19 on 2025-04-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0018_alter_exam_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multilevel.exam', verbose_name='Imtihon'),
            preserve_default=False,
        ),
    ]
