# Generated by Django 4.2.19 on 2025-05-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0019_alter_usertest_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='level',
            field=models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1'), ('multilevel', 'Multilevel'), ('tys', 'TYS')], default='multilevel', max_length=20, verbose_name='Daraja'),
        ),
    ]
