# Generated by Django 4.2.19 on 2025-06-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0020_alter_exam_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='preparation_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Preparation time for speaking questions in seconds.', null=True, verbose_name='Preparation Time (seconds)'),
        ),
        migrations.AddField(
            model_name='question',
            name='response_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Response time for speaking questions in seconds.', null=True, verbose_name='Response Time (seconds)'),
        ),
    ]
