# Generated by Django 4.2.19 on 2025-07-19 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0020_alter_exam_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Yaratilgan vaqti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('off', 'Off')], default='active', max_length=20, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti"),
        ),
    ]
