# Generated by Django 4.2.19 on 2025-07-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0021_exam_created_at_exam_status_exam_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('off', 'Off')], default='active', max_length=20, verbose_name='Holati'),
        ),
    ]
