# Generated by Django 4.2.19 on 2025-07-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0021_question_preparation_time_question_response_time'),
        ('multilevel', '0022_remove_exam_created_at_remove_exam_updated_at_and_more'),
    ]

    operations = [
    ]
