# Generated by Django 4.2.19 on 2025-08-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0023_merge_20250730_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user_answer',
            field=models.CharField(blank=True, max_length=9000, null=True, verbose_name='Foydalanuvchi javobi'),
        ),
    ]
