# Generated by Django 4.2.19 on 2025-08-21 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0024_alter_useranswer_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='response_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Response time for writing tests in seconds.', null=True, verbose_name='Response Time (seconds)'),
        ),
        migrations.AddField(
            model_name='test',
            name='upload_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Upload time for writing tests in seconds.', null=True, verbose_name='Upload Time (seconds)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='level',
            field=models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1'), ('multilevel', 'CEFR'), ('tys', 'TYS')], default='multilevel', max_length=20, verbose_name='Daraja'),
        ),
        migrations.CreateModel(
            name='WritingTestTimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('response_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Javob berish boshlanish vaqti')),
                ('upload_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Rasm yuklash boshlanish vaqti')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='Yuborish vaqti')),
                ('response_time_used', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ishlatilgan javob vaqti (sekund)')),
                ('upload_time_used', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ishlatilgan yuklash vaqti (sekund)')),
                ('response_time_limit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Javob vaqti chegarasi (sekund)')),
                ('upload_time_limit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Yuklash vaqti chegarasi (sekund)')),
                ('is_time_exceeded', models.BooleanField(default=False, verbose_name='Vaqt oshib ketgan')),
                ('status', models.CharField(choices=[('started', 'Boshlangan'), ('responding', 'Javob berilmoqda'), ('uploading', 'Yuklanmoqda'), ('completed', 'Yakunlangan'), ('time_exceeded', 'Vaqt oshib ketgan')], default='started', max_length=20, verbose_name='Holati')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multilevel.question', verbose_name='Savol')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multilevel.test', verbose_name='Test')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multilevel.testresult', verbose_name='Test natijasi')),
            ],
            options={
                'verbose_name': 'Writing test vaqti',
                'verbose_name_plural': 'Writing test vaqtlari',
                'unique_together': {('test_result', 'question')},
            },
        ),
    ]
