# Generated by Django 4.2.19 on 2025-08-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0025_test_response_time_test_upload_time_alter_exam_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WritingTestTimeTracking',
        ),
    ]
