# Generated by Django 4.2.19 on 2025-08-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0026_delete_writingtesttimetracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Savol Rasmi'),
        ),
        migrations.CreateModel(
            name='TestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tests/pictures/', verbose_name='Rasm')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='multilevel.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test rasmi',
                'verbose_name_plural': 'Test rasmlari',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='questions/', verbose_name='Rasm')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='multilevel.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Savol rasmi',
                'verbose_name_plural': 'Savol rasmlari',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
