# Generated by Django 4.2.19 on 2025-08-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0027_alter_question_picture_testimage_questionimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['level', 'order_id'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AddField(
            model_name='exam',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=0, help_text="Imtihonlar ro'yxatida ko'rsatilish tartibi. Avtomatik beriladi, lekin o'zgartirish mumkin.", verbose_name='Tartib raqami'),
        ),
    ]
