# Generated by Django 4.2.19 on 2025-10-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0002_manual_review_models'),
        ('multilevel', '0028_alter_exam_options_exam_order_id'),
    ]

    operations = [
    ]
