# Generated by Django 4.2.19 on 2025-10-12 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_alter_user_balance'),
        ('multilevel', '0032_fix_all_cascade_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Tekshiruvchi',
                'verbose_name_plural': 'Tekshiruvchilar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.AlterModelOptions(
            name='manualreview',
            options={'ordering': ['-created_at'], 'verbose_name': "Qo'lda Tekshiruv", 'verbose_name_plural': "Qo'lda Tekshiruvlar"},
        ),
        migrations.AlterModelOptions(
            name='questionscore',
            options={'ordering': ['question_number'], 'verbose_name': 'Savol Balli', 'verbose_name_plural': 'Savol Ballari'},
        ),
        migrations.AlterModelOptions(
            name='reviewlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tekshiruv Jurnal', 'verbose_name_plural': 'Tekshiruv Jurnallari'},
        ),
        migrations.AlterModelOptions(
            name='submissionmedia',
            options={'ordering': ['section', 'question_number', 'uploaded_at'], 'verbose_name': 'Topshiriq Fayli', 'verbose_name_plural': 'Topshiriq Fayllar'},
        ),
        migrations.AlterField(
            model_name='manualreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='manualreview',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tekshirilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='manualreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Tekshiruvchi'),
        ),
        migrations.AlterField(
            model_name='manualreview',
            name='section',
            field=models.CharField(choices=[('writing', 'Yozish'), ('speaking', 'Gapirish')], max_length=20, verbose_name="Bo'lim"),
        ),
        migrations.AlterField(
            model_name='manualreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('reviewing', 'Tekshirilmoqda'), ('checked', 'Tekshirilgan')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='manualreview',
            name='total_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Umumiy ball'),
        ),
        migrations.AlterField(
            model_name='manualreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='questionscore',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='questionscore',
            name='manual_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_scores', to='multilevel.manualreview', verbose_name="Qo'lda tekshiruv"),
        ),
        migrations.AlterField(
            model_name='questionscore',
            name='question_number',
            field=models.PositiveSmallIntegerField(verbose_name='Savol raqami'),
        ),
        migrations.AlterField(
            model_name='questionscore',
            name='score',
            field=models.FloatField(verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='action',
            field=models.CharField(max_length=50, verbose_name='Harakat'),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='manual_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='multilevel.manualreview', verbose_name="Qo'lda tekshiruv"),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='new_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Yangi ball'),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='old_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Eski ball'),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='question_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Savol raqami'),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tekshiruvchi'),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('listening', 'Tinglash'), ('reading', "O'qish"), ('writing', 'Yozish'), ('speaking', 'Gapirish')], max_length=20, verbose_name="Bo'lim turi"),
        ),
        migrations.AlterField(
            model_name='submissionmedia',
            name='file',
            field=models.FileField(upload_to='submissions/%Y/%m/%d/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='submissionmedia',
            name='file_type',
            field=models.CharField(choices=[('image', 'Rasm'), ('audio', 'Audio')], default='image', max_length=10, verbose_name='Fayl turi'),
        ),
        migrations.AlterField(
            model_name='submissionmedia',
            name='question_number',
            field=models.PositiveSmallIntegerField(verbose_name='Savol raqami'),
        ),
        migrations.AlterField(
            model_name='submissionmedia',
            name='section',
            field=models.CharField(choices=[('writing', 'Yozish'), ('speaking', 'Gapirish')], max_length=20, verbose_name="Bo'lim"),
        ),
        migrations.AlterField(
            model_name='submissionmedia',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='multilevel.testresult', verbose_name='Test natijasi'),
        ),
        migrations.AlterField(
            model_name='submissionmedia',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt'),
        ),
    ]
