# Generated by Django 4.2.19 on 2025-10-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0033_reviewerproxy_alter_manualreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualreview',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram xabar ID'),
        ),
    ]
