# Generated by Django 4.2.19 on 2025-10-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilevel', '0034_add_telegram_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='is_checked',
            field=models.BooleanField(default=False, help_text="Barcha sectionlar to'liq baholanganda True bo'ladi", verbose_name='Tekshirilgan'),
        ),
    ]
