# Generated by Django 4.2.19 on 2025-08-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Foydalanuvchining ismi', max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(help_text='Foydalanuvchining familiyasi', max_length=100, verbose_name='Familiya')),
                ('phone_number', models.CharField(help_text='Telefon raqami (+998 formatida)', max_length=20, verbose_name='Telefon raqami')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_review', "Ko'rib chiqilmoqda"), ('approved', 'Qabul qilindi')], default='new', help_text='Ariza holati', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('notes', models.TextField(blank=True, help_text='Admin izohlari', null=True, verbose_name='Izohlar')),
            ],
            options={
                'verbose_name': "Kursga ro'yxatdan o'tgan foydalanuvchi",
                'verbose_name_plural': "Kursga ro'yxatdan o'tgan foydalanuvchilar",
                'ordering': ['-created_at'],
            },
        ),
    ]
