# Generated by Django 4.2.19 on 2025-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AddField(
            model_name='payment',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
