# Generated by Django 4.2.19 on 2025-04-02 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multilevel', '0017_usertest_exam_usertest_transaction_id_and_more'),
        ('payment', '0003_remove_payment_test_payment_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='To‘lov summasi')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tranzaksiya ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'To‘landi'), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=20, verbose_name='To‘lov holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multilevel.exam', verbose_name='Imtihon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Exam Payment',
                'verbose_name_plural': 'Exam Payments',
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
