# Generated by Django 4.2.19 on 2025-04-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_exampayment_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exampayment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='exampayment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='exampayment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='exampayment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='To‘langanmi'),
        ),
        migrations.AddField(
            model_name='exampayment',
            name='payment_method',
            field=models.CharField(default='payme', max_length=50, verbose_name='To‘lov usuli'),
        ),
    ]
