# Generated by Django 4.2.19 on 2025-04-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_exampayment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampayment',
            name='amount',
        ),
    ]
