# Generated by Django 4.2.19 on 2025-04-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_exampayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampayment',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='To‘lov miqdori'),
            preserve_default=False,
        ),
    ]
