# Generated by Django 4.2.19 on 2025-04-03 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_exampayment_created_at_exampayment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampayment',
            name='updated_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
