# Generated by Django 4.2.19 on 2025-04-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_exampayment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampayment',
            name='transaction_id',
        ),
    ]
