# Generated by Django 4.2.19 on 2025-04-28 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0011_remove_exampayment_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Balans (UZS)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi Balansi',
                'verbose_name_plural': 'Foydalanuvchi Balanslari',
            },
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Miqdor (UZS)')),
                ('transaction_type', models.CharField(choices=[('topup', 'Balans To‘ldirish'), ('deduct', 'Balansdan Ayirish')], max_length=10, verbose_name='Tranzaksiya Turi')),
                ('description', models.CharField(max_length=255, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Balans Tranzaksiyasi',
                'verbose_name_plural': 'Balans Tranzaksiyalari',
            },
        ),
    ]
