# Generated by Django 4.2.19 on 2025-05-05 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0012_userbalance_balancetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name="To'lov miqdori")),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langanmi")),
                ('payment_method', models.CharField(default='payme', max_length=50, verbose_name="To'lov usuli")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Balans to'lovi",
                'verbose_name_plural': "Balans to'lovlari",
            },
        ),
        migrations.AlterModelOptions(
            name='userbalance',
            options={'verbose_name': 'Foydalanuvchi balansi', 'verbose_name_plural': 'Foydalanuvchilar balanslari'},
        ),
        migrations.RemoveField(
            model_name='exampayment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='balance',
        ),
        migrations.AddField(
            model_name='userbalance',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Balans miqdori'),
        ),
        migrations.AlterField(
            model_name='exampayment',
            name='amount',
            field=models.IntegerField(verbose_name="To'lov miqdori"),
        ),
        migrations.AlterField(
            model_name='exampayment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name="To'langanmi"),
        ),
        migrations.AlterField(
            model_name='exampayment',
            name='payment_method',
            field=models.CharField(default='balance', max_length=50, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_balance', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.DeleteModel(
            name='BalanceTransaction',
        ),
    ]
