# Generated by Django 4.2.19 on 2025-05-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_balancepayment_alter_userbalance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exampayment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='exampayment',
            name='amount',
            field=models.IntegerField(verbose_name='To‘lov miqdori'),
        ),
        migrations.AlterField(
            model_name='exampayment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='To‘langanmi'),
        ),
        migrations.AlterField(
            model_name='exampayment',
            name='payment_method',
            field=models.CharField(default='payme', max_length=50, verbose_name='To‘lov usuli'),
        ),
        migrations.DeleteModel(
            name='BalancePayment',
        ),
        migrations.DeleteModel(
            name='UserBalance',
        ),
    ]
