# Generated by Django 4.2.19 on 2025-07-27 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_exampayment_created_at_exampayment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
    ]
